Add files via upload
added manuelt, da jeg fik mange fejlmeldinger

hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
18:31:11.127: [Deleøkonomi] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/main:refs/heads/main --set-upstream
error: failed to push some refs to 'https://github.com/norskemarcus/Dele-konomi.git'